name: Get Last Commit Time
on:
  push:
    branches:
      - main

jobs:
  get-last-commit-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Last Commit Time
        run: |
          const fetch = require("node-fetch");

          // Get the repository owner and name
          const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");

          // Make a GET request to fetch the commit information
          const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/commits?per_page=1`);
          const data = await response.json();

          // Extract the last commit time from the response
          const lastCommitTime = data[0].commit.committer.date;

          console.log(`Last Commit Time: ${lastCommitTime}`);
